version: "3.8"
services:
  go:
    container_name: go
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./backend/src
        target: /go/src
  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_DB: shopping_reminder
      POSTGRES_USER: 38koo
      POSTGRES_PASSWORD: ${password}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
