import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import { Header } from "../Header";
import { useRouter } from "next/router";
import { Box } from "@yamada-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const Layout = ({ children }: { children: React.ReactNode }) => {
  const router = useRouter();
  const isTopPage = router.asPath === "/";

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {!isTopPage && <Header />}
        <Box pt={"8rem"} pb={"2rem"}>
          {children}
        </Box>
      </main>
    </>
  );
};
